Allow loading of images via OpenCV
codeproject/CodeProject.AI-Server pull request #110
Opened 2024-04-21 18:12 UTC by seth-planet

Image resizing is so much faster with OpenCV due to threading and vector optimizations. In theory it should be as fast as 'pillow-simd', but in practice seems to be even 4x faster than 'pillow-simd'. On my Mac, OpenCV resizes 10x faster than default pillow (non-SIMD). Unfortunately, the OpenCV package is also 10x the size of pillow, too.

Note: PR currently proposed and untested.

For performance testing, see my post here:
https://ipcamtalk.com/threads/codeproject-ai-version-2-5.74304/page-21#post-846822

2024-04-26 12:57 UTC, ChrisMaunder requested changes
I love this idea: Just a couple of reviews though. The code doesn't seem to work as-is.

2024-04-26 12:57 UTC, ChrisMaunder commented on src/SDK/Python/request_data.py
> +                return cv.imdecode(np.frombuffer(img_stream, dtype=np.uint8), cv.IMREAD_COLOR)
img_stream hasn't yet been declared or assigned.

2024-04-26 12:57 UTC, ChrisMaunder commented on src/SDK/Python/request_data.py
> +    def get_image(self, index : int, module: str = 'pil'):
I would add `-> Union[Image, numpy.ndarray]:` as a return type hint

2024-04-26 15:30 UTC, seth-planet commented
Good to hear you’re on board with it; should be fixed now! ~Sethvia iPhoneOn Apr 26, 2024, at 5:57 AM, ChrisMaunder ***@***.***> wrote:﻿
@ChrisMaunder requested changes on this pull request.

I love this idea: Just a couple of reviews though. The code doesn't seem to work as-is.

In src/SDK/Python/request_data.py:
>                  return None
 
-            img_file    = self.files[index]
-            img_dataB64 = img_file["data"]
-            img_bytes   = base64.b64decode(img_dataB64)
-            
-            with io.BytesIO(img_bytes) as img_stream:
-                img = Image.open(img_stream).convert("RGB")
-                return img
+            if module == 'opencv':
+                assert 'cv' in sys.modules and 'np' in sys.modules
+                return cv.imdecode(np.frombuffer(img_stream, dtype=np.uint8), cv.IMREAD_COLOR)

img_stream hasn't yet been declared or assigned.



In src/SDK/Python/request_data.py:
> @@ -135,11 +143,12 @@ def add_file(self, file_name: str) -> None:
             return
         self.payload["files"].append({ "data": RequestData.encode_file_contents(file_name) })
 
-    def get_image(self, index : int) -> Image:
+    def get_image(self, index : int, module: str = 'pil'):

I would add -> Union[Image, numpy.ndarray]: as a return type hint

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-26 16:04 UTC, ChrisMaunder commented
Just merging this and will try and test tonight. Too much on my plate today. Getting worried beer o’clock could be compromised today.

cheers
Chris

> On Apr 26, 2024, at 11:30 AM, Seth Price ***@***.***> wrote:
> 
> 
> Good to hear you’re on board with it; should be fixed now! ~Sethvia iPhoneOn Apr 26, 2024, at 5:57 AM, ChrisMaunder ***@***.***> wrote:﻿ 
> @ChrisMaunder requested changes on this pull request. 
> 
> I love this idea: Just a couple of reviews though. The code doesn't seem to work as-is. 
> 
> In src/SDK/Python/request_data.py: 
> > return None 
> 
> - img_file = self.files[index] 
> - img_dataB64 = img_file["data"] 
> - img_bytes = base64.b64decode(img_dataB64) 
> - 
> - with io.BytesIO(img_bytes) as img_stream: 
> - img = Image.open(img_stream).convert("RGB") 
> - return img 
> + if module == 'opencv': 
> + assert 'cv' in sys.modules and 'np' in sys.modules 
> + return cv.imdecode(np.frombuffer(img_stream, dtype=np.uint8), cv.IMREAD_COLOR) 
> 
> img_stream hasn't yet been declared or assigned. 
> 
> 
> 
> In src/SDK/Python/request_data.py: 
> > @@ -135,11 +143,12 @@ def add_file(self, file_name: str) -> None: 
> return 
> self.payload["files"].append({ "data": RequestData.encode_file_contents(file_name) }) 
> 
> - def get_image(self, index : int) -> Image: 
> + def get_image(self, index : int, module: str = 'pil'): 
> 
> I would add -> Union[Image, numpy.ndarray]: as a return type hint 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
> —
> Reply to this email directly, view it on GitHub <https://github.com/codeproject/CodeProject.AI-Server/pull/110#issuecomment-2079620991>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABDWW2MJ3LAKKS7PIUR2S4DY7JXLHAVCNFSM6AAAAABGRSE7FCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANZZGYZDAOJZGE>.
> You are receiving this because you were mentioned.
>

2024-04-26 16:48 UTC, seth-planet commented
We should schedule a zoom hangout around beer o'clock sometime!

2024-04-27 03:54 UTC, MikeLud commented
> We should schedule a zoom hangout around beer o'clock sometime!

Count me in.

2024-04-27 21:47 UTC, ChrisMaunder commented
I've merged the changes outside this pull request due to the faffing around we were doing with splitting out the repos.  Will organise zoom call for this coming week

2024-04-27 21:47 UTC, closed without merging